Repository GSG-CF04/ToDoList_04, pull requests merged in 2021-11, with the labels that each got.

#2 Create folder structure index.html, style.css, todo.js and assets folder
  index.html
  style.css
  todo.js
Labels: approved

#4 Update Readme file
  README.md
Labels: Done

#6 build html structure
  index.html
Labels: awaiting-review

#8 Build Css Style
  index.html
  style.css
Labels: request-change

#11 Add Theme selector functionality and local storage
  .vscode/settings.json
  index.html
  todo.js
Labels: Done

#12 Add Task to todo list and buttons related to it
  index.html
  todo.js
Labels: awaiting-review

#14 function to toggle checked tasks and delete tasks
  style.css
  todo.js
Labels: awaiting-review

#16 Add Tasks to local storage and display them
  todo.js
Labels: awaiting-review

#27 Fix button layout
  style.css
  todo.js
Labels: awaiting-review

#26 delete-items
  todo.js
Labels: awaiting-review
